version: "3"

services:
  web:
    image: nextcloud-alpine
    volumes:
      - ./data:/usr/share/webapps/nextcloud/config
      - ./config:/usr/share/webapps/nextcloud/config
    ports:
      - "8080:8080"
